# 应用名称
spring:
  application:
    name: eureka-server

# 应用服务 WEB 访问端口
server:
  port: 8800

eureka:
  client:
    # 不向注册中心注册自己
    register-with-eureka: false
    # 不主动发现别人
    fetchRegistry: false
    # 声明注册中心的地址
    service-url:
      defaultZone: http://localhost:8800/eureka



